### ISSUE TITLE
invalid link

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [martmists/api-docs#2]
https://martmists.tk/api/ isnt up or isnt valid

**Comment by martmists** [comment]
Why are you trying to access that page, it's unused, would serve no purpose and isn't mentioned anywhere in the docs as an endpoint.

**Comment by gidoBOSSftw5731** [comment]
Its on the front page of your gitbub...

```
documentation on how to use my API http://martmists.tk/api/
```

**Comment by martmists** [comment]
It denotes the base URL for the endpoints, and is further unrelated to all endpoints you'll want to use
